### ISSUE TITLE
Meta info set error

### ISSUE THREAD

**Issue by aholik** [moreartyjs/moreartyjs#39]
The following snippet was working with version 0.7.4:

```js
var Morearty = require('Morearty');
var ctx = Morearty.createContext({
  foo: 'bar'
});
var binding = ctx.getBinding();
binding.sub('foo').meta().set('foo-meta');

console.log(ctx.getBinding().toJS()); 
// { foo: 'bar' }
console.log(binding.sub('foo').meta().toJS()); 
// foo-meta
console.log(binding.sub('foo').toJS());
// bar
```

With v0.7.5 it fails when setting meta value:

```bash
r:\playground\js\node_modules\Morearty\src\Binding.js:66
  return rootValue.updateIn(effectivePath, UNSET_VALUE, function (value) {
                   ^
TypeError: Cannot call method 'updateIn' of undefined
    at setOrUpdate (r:\playground\js\node_modules\Morearty\src\Binding.js:66:20)
    at updateValue (r:\playground\js\node_modules\Morearty\src\Binding.js:73:25)
    at update (r:\playground\js\node_modules\Morearty\src\Binding.js:218:22)
    at Object.freeze.set (r:\playground\js\node_modules\Morearty\src\Binding.js:438:5)
    at Object.<anonymous> (r:\playground\js\mty.js:6:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by Tvaroh** [comment]
Thanks, will look into this asap.

**Comment by Tvaroh** [comment]
@aholik pass initial meta info as a second argument to `createContext` like this:

```javascript
var ctx = Morearty.createContext({
  foo: 'bar'
}, {});
```

This parameter is [required](https://rawgit.com/moreartyjs/moreartyjs/master/doc/Morearty.html#createContext) and unfortunately I can't make it optional since following `options` parameter is also an optional object. It was working in the previous version by a coincidence.

I've added saner arguments checks and appropriate [tests](https://github.com/moreartyjs/moreartyjs/blob/master/test/Morearty.js#L82) (will be included in next release).

Thanks for the feedback.

**Comment by aholik** [comment]
Thanks for the quick response. Please correct the [app bootstrapping](https://github.com/moreartyjs/moreartyjs/wiki/Bootstrapping%20the%20app#creating-context) wiki as well. Thanks again.

**Comment by Tvaroh** [comment]
Nice catch, thanks!
